version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  rest-api:
    build:
      context: .
      dockerfile: rest-api.Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - 80:80
    depends_on:
      - rest-api

